import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  return (
    <>
        <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='picture-ctn text-center'>
        <Image className="picture"src="/travelPic.png"
          alt="Main Picture"
          width={1000}
          height={500}
        />
      </div>
      <div>
        <h1 className={styles.content}>TravelR</h1>
        <h1 className={styles.content}>TravelR</h1>
        <h1 className={styles.content}>TravelR</h1>
        <h1 className={styles.content}>TravelR</h1>
      </div>
    </>
    
  )
}